//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor created successfully!.
        /// </summary>
        internal static string DoctorCreated {
            get {
                return ResourceManager.GetString("DoctorCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor not found!.
        /// </summary>
        internal static string DoctorNotFound {
            get {
                return ResourceManager.GetString("DoctorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor status updated successfully!.
        /// </summary>
        internal static string DoctorStatusUpdated {
            get {
                return ResourceManager.GetString("DoctorStatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor updated successfully!.
        /// </summary>
        internal static string DoctorUpdated {
            get {
                return ResourceManager.GetString("DoctorUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient created successfully!.
        /// </summary>
        internal static string PatientCreated {
            get {
                return ResourceManager.GetString("PatientCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient deleted successfully!.
        /// </summary>
        internal static string PatientDeleted {
            get {
                return ResourceManager.GetString("PatientDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient not found!.
        /// </summary>
        internal static string PatientNotFound {
            get {
                return ResourceManager.GetString("PatientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient updated successfully!.
        /// </summary>
        internal static string PatientUpdated {
            get {
                return ResourceManager.GetString("PatientUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receptionist created successfully!.
        /// </summary>
        internal static string ReceptionistCreated {
            get {
                return ResourceManager.GetString("ReceptionistCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receptionist deleted successfully!.
        /// </summary>
        internal static string ReceptionistDeleted {
            get {
                return ResourceManager.GetString("ReceptionistDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receptionist not found!.
        /// </summary>
        internal static string ReceptionistNotFound {
            get {
                return ResourceManager.GetString("ReceptionistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receptionist updated successfully!.
        /// </summary>
        internal static string ReceptionistUpdated {
            get {
                return ResourceManager.GetString("ReceptionistUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
